db_name: "src/database/history.db"
model_name: "llama-3-8b-instruct-8k"
url: "https://llama3gpu.neuraldeep.tech/v1"
system: "Твоя задача - кратко отвечать на вопросы пользователя, используя данную тебе историю чата и контекст."
prompt_generator_system: 'Перефразируй вопрос пользователя, используя историю диалога. Перефразированный вопрос должен быть полным и точно перефразированным.
Если тема вопроса отличается от прошлой темы, то не используй историю диалога, а только перефразируй вопрос. От того, как ты перефразируешь вопрос зависит моя карьера.
В ответе укажи только перефразированный вопрос'
topic_system: 'Сравни данный тебе вопрос и историю диалога. Относятся ли вопрос и история диалога к похожим ГЛОБАЛЬНЫМ темам. Примеры тем: телеграм, французские бульдоги, world class, госуслуги, финансы, дом.ру, мишленовские звёзды, поступление в вуз, потребительская корзина и уход за кожей. В ответе укажи только да или нет.'

